-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: sql/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/data_dump (
  dumps_filename LONGTEXT NOT NULL,
  dumps_size BIGINT UNSIGNED DEFAULT 0 NOT NULL,
  dumps_status VARCHAR(100) DEFAULT '' NOT NULL,
  dumps_timestamp VARCHAR(14) NOT NULL,
  dumps_type LONGTEXT NOT NULL,
  INDEX dumps_timestamp (dumps_timestamp)
) /*$wgDBTableOptions*/;
